### ISSUE TITLE
dll filename error.

### ISSUE THREAD

**Issue by rereser** [IDA-RE-things/Chrome-xp-api-adapter#14]
xp sp3 supermium r6 will not start with the latest chrome-xpapi-adapter_x86.b5057.
reason for that is a wrong filename.
"chrome-xpapi-adapter.5057.dll" should be renamed to "chrome-xpapi-adapter.dll".
secondly: in the "chrome-xpapi-adapter_x86.b5056.zip" the "chrome-win7-xp-api-router.dll" is version 1.2.0.5055, not 1.2.0.5056.
v5057 solves high one core cpu use on the win32/612 issue video example page.

**Comment by IDA-RE-things** [comment]
> "chrome-xpapi-adapter.5057.dll" should be renamed to "chrome-xpapi-adapter.dll".

Yes, I think user understand that DLL with suffix .5057 should be ranmed to without that suffix.
I rename it such way to point user, that only this DLL have changed compared to previous archive.
But I agree with you, I will rename it on my side to prevent such confusions. And will reupload.

> secondly: in the "chrome-xpapi-adapter_x86.b5056.zip" the "chrome-win7-xp-api-router.dll" is version 1.2.0.5055, not 1.2.0.5056.

Yes, its because no changes was made in that dll, so I keepd it untouched to prevent additional semi-manual optimization phase.
But I will change it (also) in next upload.

> v5057 solves high one core cpu use on the win32/612 issue video example page.

Yes, I create it to resolve that issue. It work on my computers. Thanx fo testing.

**Comment by rereser** [comment]
thank you for your continued efforts.
