### ISSUE TITLE
Latest b5078 BROKEN for both 126-r3_32 and 126-r4_32 on VistaSP2 x86

### ISSUE THREAD

**Issue by Vangelis66** [IDA-RE-things/Chrome-xp-api-adapter#24]
**OS**: **Windows Vista SP2 32-bit**, with all updates up to EoS (plus select WS2008 SP2 updates manually installed)

H/W specifics: 

Mechanical HDD, 500 GB (C+D partitions, C ~ 160GB)
**CPU**: Intel Core2 Duo  T5250 @1.50GHz
**iGPU**: Mobile Intel 965 Express Chipset Family
**RAM**=3 GB (2+1)

Greetings :smile:;  I have been happily running "portabilised" (_X-Launcher_) installations of **Supermium 32-bit** of versions `121-r3`, `122-r6`, `124-r2` and `126-r3` (each with its own profile) with **b5073** of your alternate lib :+1: ; I'm using just 4 DLLs adjacent to the main `chrome.exe`: 

1. [chrome-win7-xp-api-router-Vista.dll (v1.2.0.5069) =>] progwrp.dll (v1.2.0.5069)
2. chrome-xpapi-adapter.dll (v1.2.0.5073)
3. DWrite.dll (v1.5.0.2311)
4. DWTxp.dll (v1.2.0.5077)

and this arrangement works fine up to (and including) previous **Supermium 126-r3** .

Now, before updating **Supermium** to the **latest release** (`126-r4`), I first tried to **update just your lib**, since it is stated that **v1.2.0.5078** is compatible with **Sm-126-r3+** (and incompatible with previous releases); 

1. [chrome-win7-xp-api-router-Vista.dll (v1.2.0.5078) =>] progwrp.dll (v1.2.0.5078)
2. chrome-xpapi-adapter.dll (v1.2.0.5078)
3. DWrite.dll (v1.5.0.2311)
4. DWTxp.dll (v1.2.0.5077)

Now, imagine my surprise when I found out that on my OS (see opening lines) your lib DOESN'T WORK :cry: ; in Windows Task Manager I can see two `chrome.exe` processes "flashing" for fractions of a second and then... nada; **Supermium-126-r3** won't launch at all - no error message displayed either...

I then went on and **updated the browser itself** to `126-r4`, hoping that your **b5078** would be at least working there; but no, same thing with r3, **r4 won't launch at all**...

Downgrading b5078 to b5073 doesn't fix it either, because while **b5073 IS compatible with 126-r3, it isn't with 126-r4** ; so, to run 126-r4 here I have no option but to use the original (upstream) implementation (**progwrp.dll** v1.1.0.5023/5024 works fine :wink: ) ...

I realise I may be one of the two :smile: **Vista users in need of your own lib**, but PLEASE, can you investigate and hopefully provide build 507**9** which enables Supermium-126-r3/r4[-x86] to launch on **Vista SP2 x86** ?

It's unfortunate that while Vista sits between XP and 7, it's different **to both**; more so to XP, of course, being NT 6.0, but different enough to NT 6.1, too... FWIW, I've tried both fresh and old/dirty Supermium profiles, so the problem on Vista does not seem related to a flag/pref/setting/etc.

Thanks for all your hard efforts!

**Comment by IDA-RE-things** [comment]
Hi, before uploading, I have tested build b5078 only for runnig on real XP SP3 and Win7. because I have used it on real hardware.
Ok, if it dont works with Vista, I will check whats happened, running it under virtual machine now.
It has experimental features, so it was not stable build., in opposed to build b5073.

You are right, that you are one of 1-2 users with this OS, so don't be too surprised, when you do beta-testing for it :).

UPD: I have found that my current version works also on Vista, and with versions of Sm form 121 to 126-r4 (because of my different changes after released b5078 version). But there are some things (not in my code, but in Chrome.dll code), which I implement/investigate before next release. It will be soon.

**Comment by IDA-RE-things** [comment]
Have uploaded build of just DLL:  5079-beta. 
It works with my VirtualPC-2007 with Vista VM.
try it on real machine for more deep testing., I mean using HW acceleration etc.

**Comment by Vangelis66** [comment]
> You are right, that you are one of 1-2 users with this OS, so don't be too **surprised**, when you do **beta-testing** for it :).

Us few **Vista** users do acknowledge our limited numbers, and not only as far as **Supermium** is concerned :wink: ; TBH, I did not think for a mere second that I was "beta-testing" **b5078** :smile: ; but I now get it that you're not routinely checking your releases under **Vista SP2 OS**... It's understandable, though...

> Have uploaded build of just DLL: 5079-beta.
It works with my VirtualPC-2007 with Vista VM.
try it on real machine for more deep testing.,

OK, many thanks :+1: ; I have now prepared the following set of 4 DLLs: 

1. [chrome-win7-xp-api-router-Vista.dll (v1.2.0.5078) =>] progwrp.dll (v1.2.0.5078)
2. [chrome-xpapi-adapter.1.2.0.5079.beta.dll =>] chrome-xpapi-adapter.dll (v1.2.0.5079)
3. DWrite.dll (v1.5.0.2311)
4. DWTxp.dll (v1.2.0.5077)

and put them adjacent to main `chrome.exe` v**126**.0.6478.**254** ; all upstream DLLs removed :smile: ; well, I can confirm that on my _real machine_ `Sm-v126-r4_32` now (finally) launches and opens as expected! Congrats! Below is `chrome://gpu/` with `chrome://flags/#ignore-gpu-blocklist` set to `Enabled`: 

![gpu](https://github.com/user-attachments/assets/4ede6377-d3dc-495e-8948-347472cb4275)

Under Vista SP2, I have no need for your patched `D3DCompiler_XP.dll` file, the browser can use original file `d3dcompiler_47.dll` inside the `126.0.6478.254` directory...

Thanks again for such a swift and successful response (no time now, sadly, for extensive tests, it's bed-time :stuck_out_tongue_winking_eye: ) .

**Comment by Vangelis66** [comment]
> But there are some things (not in my code, but in Chrome.dll code), which I implement/investigate **before next release. It will be soon**.

Greetings :smile: ; I want to mark this issue as `Closed` (my `Sm-v126-r5_x86` runs fine on **Vista SP2 32-bit** :tada: ), but your **latest fix/DLL** is still marked as "**beta**" (`chrome-xpapi-adapter_x86.b5080.beta4_int.upd_of_5078.zip)`; will there be soon (as promised _one month ago_ :wink: ) a **final/stable** release of your lib(s)? 

Many thanks for all that you do! :heart:

**Comment by IDA-RE-things** [comment]
:), I have not released final version, because of one feature, I have not added to it, to be more "complete", -  features, implemented for v126-r3 & r4, but not fully for v126-r5, And onother one. Because have no free time...

Also one or two XP-users was having old problem, with crashing on their machines (afer moving to v124 & 126 API's ), which was not reproduced on my machines, and on their also... They dont sent me crashdumps while. But I have recommended them to update libglesv2.dll and its seems had resolved with one of users. (the discussion its not on github here). When I will see, that its not re-appeared, it can be marked as stable. 
So its still marked "beta" or "pre-release" while.

**Comment by Vangelis66** [comment]
I've just tested the recently released `v1.2.0.5081` (package `chrome-xpapi-adapter_x86.b5081-full.zip`) and it works fine :+1: _here_ (**Vista SP2 32-bit**, `Sm-v126-r5_x86`) ; closing the issue, with my best compliments along the way :heart: ; many thanks!
